# Smart Performance Analytics System

## Projenin Amacı:
Bu projenin amacı Numpy kullanarak çok boyutlu performans verileri üzerinde temel analizler yapabilmektir. Gerçek hayata benzer bir senaryo üzerinden çalışan performanslarının incelenmesi hedeflenmiştir.

## Numpy neden kullanılır?
- Çok boyutlu dizilerle çalışmayı kolaylaştırır.
- Hızlı ve verimli vektörel hesaplama yapmayı sağlar.
- Döngü kullanmadan toplu işlemler gerçekleştirmeyi mümkün kılar.

## Bu projede Kullanılan Numpy konuları:
- NumPy array oluşturma
- Numpy dizi (array) ve matrix yapıları
- İndeksleme ve slicing
- Axis kavramı
- Vektörel (toplu) işlemler
- Temel NumPy metodları


In [2]:
import numpy as np
#8-> çalışan (rows)
#6-> aylar (columns)

#8x6 boyutunda performans matrisi oluştur ve değerler 50-100 arası random olsun
performans = np.random.randint(50, 100, size=(8,6))

performans

array([[84, 79, 99, 79, 79, 97],
       [66, 77, 58, 80, 99, 51],
       [93, 87, 59, 57, 63, 83],
       [82, 77, 53, 94, 88, 97],
       [95, 79, 52, 91, 53, 80],
       [50, 53, 92, 51, 50, 52],
       [96, 63, 56, 99, 52, 81],
       [52, 87, 57, 85, 98, 53]])

In [3]:
#3 Array özellikleri (shape, ndim, dtype)
#Toplam eleman sayısı

#Dizi boyutu shape (row, column)
diziBoyutu = performans.shape
print(f"Shpae of array: {diziBoyutu}")

#Dizinin kaç boyutlu olduğu 
kacBoyutlu = performans.ndim
print(f"Number of dimensions: {kacBoyutlu}")

#Dizinin veri tipi
veriTipi = performans.dtype
print(f"Data type of array: {veriTipi}")

#Toplam eleman sayısı
toplamEleman = performans.size
print(f"Total number of elements: {toplamEleman}")

Shpae of array: (8, 6)
Number of dimensions: 2
Data type of array: int64
Total number of elements: 48


In [8]:
#4 Numpy indeksleme

#İlk çalışanın tüm aylarını seç -- çalışanlar satırlardı --  ilk çalışan 0. indekstir
ilkCalisan = performans[0] # -> ilk calisan
print(f"İlk çalışanın tüm ayları: {ilkCalisan}")

#Son ayın tüm çalışanlarını seç -- aylar sütunlardı -- 
sonAy = performans[:, -1] #[bütün satırlar, son sütun] yani son sütundaki bütün satırlardaki çalışanları aldık
print(f"Son ayın tüm çalışanları: {sonAy}")

#İlk 3 çalışanın ilk 2 ayını seç
ucCalisanIkiAy = performans[:3, :2] # ilk 3 çalışan 0,1,2. indekslerdir ve ilk 2 ay da 0,1. indekslerdir
print(f"İlk 3 çalışanın ilk 2 ayı:\n {ucCalisanIkiAy}")

İlk çalışanın tüm ayları: [84 79 99 79 79 97]
Son ayın tüm çalışanları: [97 51 83 97 80 52 81 53]
İlk 3 çalışanın ilk 2 ayı:
 [[84 79]
 [66 77]
 [93 87]]


In [12]:
#5 Matrix indeksleme

#Belirli bir çalışanın belirli ay skorunu al
#6. çalışanın, 4. ay performansını alalım--> 6. çalışan 5. indekstir, 4. ay da 3. indekstir
belirliCalisan = performans[5, 3]
print(f"Altıncı çalışanın 4. ay performansı: {belirliCalisan}")

#Bir alt matris (sub-matrix oluştur)
#2. ve 3. çalışanların, 4. ve 5. ay skorları
sub_matrix = performans[1:3, 3:5]
print(f"2. ve 3. çalışanların dördüncü ve beşinci ay skorları:\n {sub_matrix}")


Altıncı çalışanın 4. ay performansı: 51
2. ve 3. çalışanların dördüncü ve beşinci ay skorları:
 [[80 99]
 [57 63]]


In [14]:
#6 Numpy Operasyonlar
# Tüm skorlara +5 puan ekle
degismisSkorlar = performans + 5
print(f"Tüm skorlara 5 eklenmiş hali:\n {degismisSkorlar}")
print(" ")

#Skorları 100 ile normalize et (0-1) e çek yani
normalize = performans / 100
print(f"Normalize edilmiş skorlar:\n {normalize}")
print(" ")

#İki farklı ayın skorlarını karşılaştır (2. ay vs 5. ay)
ikiAyKarsilastirma = performans[:,5] > performans[:, 1]
print(f"Beşinci ayın skoru ikinci aydan yüksek mi?: {ikiAyKarsilastirma}")

Tüm skorlara 5 eklenmiş hali:
 [[ 89  84 104  84  84 102]
 [ 71  82  63  85 104  56]
 [ 98  92  64  62  68  88]
 [ 87  82  58  99  93 102]
 [100  84  57  96  58  85]
 [ 55  58  97  56  55  57]
 [101  68  61 104  57  86]
 [ 57  92  62  90 103  58]]
 
Normalize edilmiş skorlar:
 [[0.84 0.79 0.99 0.79 0.79 0.97]
 [0.66 0.77 0.58 0.8  0.99 0.51]
 [0.93 0.87 0.59 0.57 0.63 0.83]
 [0.82 0.77 0.53 0.94 0.88 0.97]
 [0.95 0.79 0.52 0.91 0.53 0.8 ]
 [0.5  0.53 0.92 0.51 0.5  0.52]
 [0.96 0.63 0.56 0.99 0.52 0.81]
 [0.52 0.87 0.57 0.85 0.98 0.53]]
 
Beşinci ayın skoru ikinci aydan yüksek mi?: [ True False False  True  True False  True False]


In [21]:
# 7 Numpy metotları

#çalışan bazlı ortalama (axis=1) -> satır boyunca işlem yapar
calisanOrtalama = np.mean(performans, axis=1)
print(f"Çalışan bazlı ortalama performansı:\n {calisanOrtalama}")
print(" ")

#Ay bazlı ortalama (axis=0)
ayOrtalama = np.mean(performans, axis=0)
print(f"Ay bazlı ortalama performansı: {ayOrtalama}")

#En yüksek performans
enYuksekPerf = np.max(performans)
print(f"En yüksek performans: {enYuksekPerf}")

#En düşük performans 
enDusukPerf = np.min(performans)
print(f"En düşük performans: {enDusukPerf}")

Çalışan bazlı ortalama performansı:
 [86.16666667 71.83333333 73.66666667 81.83333333 75.         58.
 74.5        72.        ]
 
Ay bazlı ortalama performansı: [77.25 75.25 65.75 79.5  72.75 74.25]
En yüksek performans: 99
En düşük performans: 50


In [24]:
#8 Numpy dizi metotları
# reshape - 8x6 = 48 di, 4x12 yapabiliriz yani 4 satır 12 sütun
reshapedData = performans.reshape(4,12)
print(f"Reshape yapılmış veri (4x12):\n {reshapedData}")
print(" ")

#transpose -> satır ve sütunlar yer değiştirir satırlar ayları, sütunlar çalışanları temsil eder
transposed = performans.T
print(f"Transpose edilmiş hali:\n {transposed}")
print(" ")

#flatten 2D'den 1D'ye çevirir yani düzleştirir
flattenData = performans.flatten()
print(f"Flatten edilmiş ve 1D hale getirilmiş hali:\n {flattenData}")


Reshape yapılmış veri (4x12):
 [[84 79 99 79 79 97 66 77 58 80 99 51]
 [93 87 59 57 63 83 82 77 53 94 88 97]
 [95 79 52 91 53 80 50 53 92 51 50 52]
 [96 63 56 99 52 81 52 87 57 85 98 53]]
 
Transpose edilmiş hali:
 [[84 66 93 82 95 50 96 52]
 [79 77 87 77 79 53 63 87]
 [99 58 59 53 52 92 56 57]
 [79 80 57 94 91 51 99 85]
 [79 99 63 88 53 50 52 98]
 [97 51 83 97 80 52 81 53]]
 
Flatten edilmiş ve 1D hale getirilmiş hali:
 [84 79 99 79 79 97 66 77 58 80 99 51 93 87 59 57 63 83 82 77 53 94 88 97
 95 79 52 91 53 80 50 53 92 51 50 52 96 63 56 99 52 81 52 87 57 85 98 53]


In [30]:
# 9 Genel performans özeti
# calisanOrtalama'yı yukarıda aldık
#En başarılı çalışan 
enBasariliCalisan = np.argmax(calisanOrtalama) #indeks veriyor
print(f"En başarılı çalışan: Çalışan {enBasariliCalisan+1}") #indeksi + 1 yaptık

#En yüksek ay ortalaması
#aybazlıortalamayı yukarıda aldık yine
enYuksekAy = np.argmax(ayOrtalama)
print(f"En yüksek ay ortalaması: Ay {enYuksekAy+1}")

#Genel ortalama performansı
genelOrtalamaPerf = np.mean(performans)
print(f"Genel ortalama performans: {genelOrtalamaPerf:.2f}")

En başarılı çalışan: Çalışan 1
En yüksek ay ortalaması: Ay 4
Genel ortalama performans: 74.12
