# Smart Sales Data Analyzer

## Projenin Amacı:
Bu projenin amacı, bir mağazanın **7 günlük satış verisini** kullanarak **yalnızca NumPy array yapıları ve metodları** ile anlamlı analizler yapmaktır.
Proje boyunca:
- Satış verileri NumPy array olarak tutulacak
- Günlük ve ürün bazlı analizler yapılacak
- NumPy’nin dizi (array) mantığı pratik olarak pekiştirilecektir

Bu proje, NumPy temel bilgilerini **gerçekçi bir senaryo** üzerinden
uygulamayı hedefler.

## Neden Numpy kullanılır ? 
- Numpy büyük veri setleriyle hızlı ve verimli çalışır.
- Çok boyutlu diziler ile matematiksel işlemleri kolaylaştırır
- Python'da bilimsel hesaplamanın temelini oluşturur
- Pandas ve Machine Learning kütüphanelerinin altyapısını anlamayı sağlar.

## Kullanılan Numpy Konuları:
- NumPy giriş
- NumPy array oluşturma
- NumPy temel metodları (`sum`, `mean`, `max`, `min` )
- NumPy metodlar (devam)
- NumPy dizi (array) metodları

In [1]:
#2- Numpy import ve veri oluşturma
import numpy as np

# 7 gün x 5 ürünlük satış verisi
sales = np.random.randint(5, 30, size = (7,5)) #5-30 arası rastgele satış adetleri, 7 gün ve 5 ürün (7 satır 5 sütun)


In [2]:
sales

array([[22, 27, 17, 18, 16],
       [ 9, 25, 16, 26,  8],
       [ 9, 21,  8, 11, 16],
       [ 8,  6, 15, 23, 12],
       [ 9, 21,  9, 24,  9],
       [27, 28, 22, 29, 26],
       [ 8,  7, 25, 19, 10]])

In [10]:
# 3- Array özellikleri
# shape, ndim, dtype ve toplam eleman sayısı

#Array boyutu - shape (satır, sütun)
sales_boyutu = sales.shape
print(f"Shape: {sales_boyutu}")

#Arrayın kaç boyutlu olduğu ndim
arrayinBoyutlu = sales.ndim
print(f"Number of dimensions (Dizinin boyutu): {arrayinBoyutlu}")

#Array içindeki veri tipi - dtype
arrayVeritipi = sales.dtype
print(f"Data type of array: {arrayVeritipi}")

#Toplam eleman sayısı - size
toplamEleman = sales.size
print(f"Total number of elements: {toplamEleman}")

Shape: (7, 5)
Number of dimensions (Dizinin boyutu): 2
Data type of array: int64
Total number of elements: 35


In [15]:
#4- Indexing and Slicing

#Belirli bir günün satışlarını al (5.günü alalım)
belirliGunSatisi = sales[4]
print(f"Beşinci günün satışları: {belirliGunSatisi}")

#Belirli bir ürünün haftalık satışını al - 2. ürün olsun -> index 1
belirliHaftalikSatis = sales[:, 1] # [satır, sütun] -> [günler, ürünler] yani [hepsini al, 2. ürünü al (indeksi 1)]
print(f"2. ürünün haftalık satışları: {belirliHaftalikSatis}")

#ilk 3 günün satışları
ilkUcGununSatis  = sales[:3, :] # -> [:3] demek 0,1,2. indeksleri al demek yani ilk 3 gün, [, :] ise tüm ürünleri al demek
print(f"İlk 3 günün satışları:\n {ilkUcGununSatis}")

Beşinci günün satışları: [ 9 21  9 24  9]
2. ürünün haftalık satışları: [27 25 21  6 21 28  7]
İlk 3 günün satışları:
 [[22 27 17 18 16]
 [ 9 25 16 26  8]
 [ 9 21  8 11 16]]


In [17]:
#5- Temel Numpy metotları

#Toplam satış (sum)
toplamSatis = sales.sum()

#Günlük ortalama satış (mean) - gün bazlı yani satır bazlı
gunlukOrtalamaSatis = sales.mean(axis=1) # axis=1 -> satır boyunca yani gün

#En yüksek satış - max
enYuksekSatis = sales.max()

#En düşük satış - min
enDusukSatis = sales.min()


print(f"Toplam satış: {toplamSatis}")
print(f"Günlük ortalama satış: {gunlukOrtalamaSatis}")
print(f"En yüksek satış: {enYuksekSatis}")
print(f"En düşük satış: {enDusukSatis}")

Toplam satış: 586
Günlük ortalama satış: [20.  16.8 13.  12.8 14.4 26.4 13.8]
En yüksek satış: 29
En düşük satış: 6


In [18]:
# 6- Axis kullanımı

#gün bazlı toplam satış
gunTopSatis = sales.sum(axis=1) #gün bazlı yani satır bazlı toplam satış
print(f"Gün bazlı toplam satış: {gunTopSatis}")

#ürün bazlı toplam satış
urunTopSatis = sales.sum(axis=0) #ürün bazlı toplam satış
print(f"Urun bazlı toplam satış: {urunTopSatis}")

#axis = 1-> satır boyunca işlem yapar yani bizim problemimizde günlere denk gelir (Yani sütunlar boyunca soldan sağa toplar )
#axis= 0 -> sütun boyunca işlem uyapar bizim problemimizde ürünlere denk gelir (Yani aslında satırlar boyunca yukarıdan aşağıya toplar)

Gün bazlı toplam satış: [100  84  65  64  72 132  69]
Urun bazlı toplam satış: [ 92 135 112 150  97]


In [22]:
#7- Numpy dizi metotları
#reshape -> Arrayin şeklini değiştirir bizim verimiz 7 x 5 = 35 elemandı
# 35 eleman korunarak farklı boyuta sokulabilir
reshaped_sale = sales.reshape(5,7) #eleman sayısı aynı sadece şekil değişir
print(f"Reshape 5x7:\n {reshaped_sale}")

print(" ")

# transpose -> satır ve sütunları yer değiştirir yani günler ve ürünler yer değiştirir
transposed = sales.T
print(f"Transposed data:\n {transposed}")
print(" ")

#flatten -> 2d boyutlu diziyi tek boyuta (vektörel) çevirir, kopya oluşturur
flattened = sales.flatten()
print(f"Flatten data:\n {flattened}")

#ravel -> kopya oluşturmadan 1D array döner
#raveled = sale.ravel()

Reshape 5x7:
 [[22 27 17 18 16  9 25]
 [16 26  8  9 21  8 11]
 [16  8  6 15 23 12  9]
 [21  9 24  9 27 28 22]
 [29 26  8  7 25 19 10]]
 
Transposed data:
 [[22  9  9  8  9 27  8]
 [27 25 21  6 21 28  7]
 [17 16  8 15  9 22 25]
 [18 26 11 23 24 29 19]
 [16  8 16 12  9 26 10]]
 
Flatten data:
 [22 27 17 18 16  9 25 16 26  8  9 21  8 11 16  8  6 15 23 12  9 21  9 24
  9 27 28 22 29 26  8  7 25 19 10]


In [27]:
#7- Çıktılar

#Toplam haftalık satış (tüm gün + tüm ürünler)
print(f"Toplam haftalık satış: {toplamSatis}")

#En çok satan ürün (ürün bazlı toplamdan)
#np.argmax() -> bir array içindeki en büyük değerin indeksini verir
enCokSatanUrun = sales.sum(axis=0) #axis=0 ürünlerdi
enCokSatanUrunIndex = np.argmax(enCokSatanUrun) #en cok satan ürünün indeksini aldık
print(f"En çok satan ürün: Ürün {enCokSatanUrunIndex + 1}") #index 0->ürün 1, biz saymaya 1 den başladığımız için 0+1=ürün1 olacak

#En iyi gün
enIyiGun = sales.sum(axis=1) #axis1 = günler
enIyiGununIndex = np.argmax(enIyiGun)
print(f"En iyi gün: Gün {enIyiGununIndex + 1}") # mesela 5. günün indeksi 4 burada index + 1 diyerek 5. gün olarak alıyoruz


Toplam haftalık satış: 586
En çok satan ürün: Ürün 4
En iyi gün: Gün 6
